apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-load-mini.fullname" . }}
  labels:
{{ include "nfs-load-mini.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nfs-load-mini.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}